import register from "./register";
import handleLogin from "./index";
import userProfile from "./user/userProfile";
import SumaryView from "./summary/sumaryView";
import comentsView from "./summary/comentsView";
import AnsweredQuestionDetail from "./summary/answeredQuestionDetail";
import QuizView from "./study/quiz/quiz";
import challangeDescription from "./study/quiz/challangeDescription";
import { getCorrectAnswers } from "./study/quiz/functions/getCorrectAnswers";
import { handleAnswerColor } from "./study/quiz/functions/handleAnswerColor";
import StudyCard from "./study/flash_cards/flash_cards";
import AiAccordion from "./study/flash_cards/components/AiAccordion";
import { StudyCardWindow } from "./study/components/StudyWindow";
import addQuestionScreen from "./study/add_screens/add_question_screen";
import { DataProvider } from "./study/add_screens/components/answers_context";
import { useCourseByID } from "./hooks/useCourseByID";
import { useUser } from "./hooks/useUser";
import LectureList from "./courses/lectures/lecture_list";
import LectureCard from "./courses/lectures/components/LectureCard";
import HomePage from "./courses/courses_list/user_courses";
import scoreboard_full from "./courses/course_detail/scoreboard_full";
import CourseDetail from "./courses/course_detail/[course_id]";
import { scoreChecker } from "./courses/course_detail/functions/scoreChecker";
import CourseItem from "./courses/components/course_item";
import Login from "./index";
import fetchCourses from "@/api/Downloaders/fetchAllCourses";
import fetchAnswers from "@/api/Downloaders/fetchAnswers";
import fetchChallange from "@/api/Downloaders/fetchChallange";
import fetchComments from "@/api/Downloaders/fetchComments";
import fetchCourseByID from "@/api/Downloaders/fetchCourseByID";
import fetchLectureDetails from "@/api/Downloaders/fetchLectureDetails";
import fetchLecturesForCourse from "@/api/Downloaders/fetchLectureForCourse";
import { getOpenAIResponse } from "@/api/Downloaders/fetchOpenAIResponse";
import fetchQuestions from "@/api/Downloaders/fetchQuestions";
import fetchScore from "@/api/Downloaders/fetchScoreboard";
import fetchAchievements from "@/api/Downloaders/fetchUserAchivements";
import fetchUserID from "@/api/Downloaders/fetchUserID";
import { fetchUserCourseCompletion } from "@/api/Downloaders/lectureCompleationDownloader";
import fetchUserData from "@/api/Downloaders/userDataDownloader";
import { post_ai_context_for_question } from "@/api/Uploaders/addAiContext";
import { Authentification } from "@/api/Authentification";
import uploadVisitedCourse from "@/api/Uploaders/addVisitedCourse";
import addComment from "@/api/Uploaders/commentUploader";
import { handleRegister } from "@/api/Uploaders/registration";
import removeVisitedCourse from "@/api/Uploaders/removeVisitedCourse";
import report_question from "@/api/Uploaders/reportQuestion";
import ScoreUploader from "@/api/Uploaders/scoreUploader";
import postQuestionWithAnswers from "@/api/Uploaders/uploadQuestion";
export { Login,register, userProfile,handleLogin,SumaryView,comentsView,AnsweredQuestionDetail,QuizView,challangeDescription,getCorrectAnswers,handleAnswerColor,StudyCard,AiAccordion,StudyCardWindow,addQuestionScreen,DataProvider,useCourseByID,useUser,LectureList,LectureCard,HomePage,scoreboard_full,CourseDetail,scoreChecker,CourseItem,fetchCourses,fetchAnswers,fetchChallange,fetchComments,fetchCourseByID,fetchLectureDetails,fetchLecturesForCourse,getOpenAIResponse,fetchQuestions,fetchScore,fetchAchievements,fetchUserID,fetchUserCourseCompletion,fetchUserData,post_ai_context_for_question,uploadVisitedCourse,addComment,handleRegister,removeVisitedCourse,report_question,ScoreUploader,postQuestionWithAnswers,Authentification};